# Warnings currently triggered
- ignore: {name: "Use ++"} # 3 hints
- ignore: {name: "Use camelCase"} # 31 hints
- ignore: {name: "Use foldr"} # 1 hint
- ignore: {name: "Use lambda-case"} # 4 hints
- ignore: {name: "Use record patterns"} # 5 hints
- ignore: {name: "Use tuple-section"} # 3 hints

# Replace a $ b $ c with a . b $ c
- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}

- group: {name: future, enabled: true}
- group: {name: teaching, enabled: true}

- ignore: {name: "Use infix"}
- ignore: {name: "Use <$>"}
