# colorize output and run in parallel
- arguments: [--color=auto, -j ]

- extensions:
  - default: false # Disallow extensions, combined with the below we tightly control them overall.
  - {name: CPP,
# Centralize CPP for different GHC versions in a single module, Pollock.CompatGHC
     within: Pollock.CompatGHC
     }
  - {name: ScopedTypeVariables,
# Limit the use of ScopedTypeVariables as well
     within: Pollock.ProcessModule
     }

# Don't suggest language extensions
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use tuple-section"}

# Replace a $ b $ c with a . b $ c
- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}

- group: {name: future, enabled: true}
- group: {name: teaching, enabled: true}

- ignore: {name: "Use infix"}
- ignore: {name: "Use <$>"}
